README.md

the badge for projects using @tinkoff/linters

docs: add codestyle badge

---

README.md
tslint/mixins/rxjs.common.tslint.json
tslint/mixins/rxjs5.5.tslint.json
tslint/mixins/rxjs6.tslint.json

Добавил правила линтера для RxJS 6+.

Added rules for RxJS 6

---

package-lock.json
package.json
packages/eslint-config/package.json
packages/linters/package.json

2.3.0 version provide too many changes, need upgrade with breaking change commit

fix: prettier version fixed to 2.2.1

---

packages/eslint-plugin/tests/__snapshots__/member-ordering.test.js.snap
packages/eslint-plugin/tests/__snapshots__/require-return-type.test.js.snap
packages/eslint-plugin/tests/member-ordering.fixture.ts
packages/eslint-plugin/tests/require-return-type.fixture.ts
tsconfig.json

-   [ ] The commit message follows [Conventional Commits](https://www.conventionalcommits.org/en/)
-   [ ] Bugfix
-   [ ] Feature
-   [x] Refactoring
The current tests are not written correctly for the TypeScript compiler
The current code is simply put in the order of their number fields so that the code does not crash with a compilation error.
-   [ ] Yes
-   [x] No

test: refactor before upgrade to @typescript-eslint v5

---

packages/stylelint-config/README.md
packages/stylelint-config/angular.js

-   [x] The commit message follows [Conventional Commits](https://www.conventionalcommits.org/en/)
-   [ ] Bugfix
-   [x] Feature
Closes # 
-   [ ] Yes
-   [x] No

feat(stylelint-config): expose configs for angular

---

.github/workflows/check.yml
package-lock.json
packages/stylelint-config/README.md
packages/stylelint-config/package.json
packages/stylelint-config/taiga-ui.js

-   [ ] The commit message follows [Conventional Commits](https://www.conventionalcommits.org/en/)
-   [ ] Bugfix
-   [x] Feature
Current stylelint doesn't support new Less compiler
https://stylelint.io/migration-guide/to-14
Support stylelint rules for Taiga-UI projects
-   [ ] Yes
-   [x] No

feat(stylelint-config): expose configs for taiga-ui

---

.lintstagedrc.js
README.md
package-lock.json
package.json

-   [x] The commit message follows [Conventional Commits](https://www.conventionalcommits.org/en/)
-   [x] Docs have been added / updated (for bug fixes / features)
-   [ ] Bugfix
-   [ ] Feature
-   [x] Documentation content changes

docs: improved README.md

---

packages/stylelint-config/angular.js

-   [x] The commit message follows [Conventional Commits](https://www.conventionalcommits.org/en/)
-   [x] Bugfix
-   [ ] Feature
-   [ ] Yes
-   [x] No

fix(stylelint-config): ignore ng-deep

---

.prettierignore
.prettierrc.js
CODE_OF_CONDUCT.md
ROADMAP.md
package-lock.json
package.json
packages/eslint-config-angular/README.md
packages/eslint-config-angular/package.json
packages/eslint-config-react/README.md
packages/eslint-config/README.md
packages/eslint-config/package.json
packages/linters/README.md
packages/linters/eslint/common/best-practices.js
packages/linters/eslint/common/formatting.js
packages/linters/package.json
packages/prettier-config/README.md
packages/prettier-config/angular.js
packages/prettier-config/package.json
packages/stylelint-config/README.md
packages/stylelint-config/package.json

-   [x] The commit message follows [Conventional Commits](https://www.conventionalcommits.org/en/)
-   [ ] Bugfix
-   [x] Feature
https://github.com/TinkoffCreditSystems/taiga-ui/issues/923
Support angular preset
-   [ ] Yes
-   [x] No

feat(prettier-config): expose configs for angular

---

package-lock.json
packages/prettier-config/angular.js
packages/prettier-config/package.json

feat(prettier-config): support xml,svg and prevent override printWidth

---

packages/prettier-config/angular.js

fix(prettier-config): use valid parser for scss files

---

package-lock.json
packages/stylelint-config/package.json

fix(stylelint-config): fix missing dependencies for less

---

packages/eslint-config-angular/internal/base.js
packages/eslint-config-angular/internal/import.js

feat(eslint-config-angular): add default ignore pattern

---

package-lock.json
packages/eslint-config-angular/internal/import.js
packages/eslint-config-angular/package.json
packages/eslint-config-angular/test/imports/__fixtures__/imports-happy.fixture.ts
packages/eslint-config-angular/test/imports/__fixtures__/imports-unhappy.fixture.ts
packages/eslint-config-angular/test/imports/__fixtures__/shared-imports.fixture.ts
packages/eslint-config-angular/test/imports/__snapshots__/imports-happy.test.js.snap
packages/eslint-config-angular/test/imports/__snapshots__/imports-unhappy.test.js.snap
packages/eslint-config-angular/test/imports/imports-happy.test.js
packages/eslint-config-angular/test/imports/imports-unhappy.test.js
tsconfig.json

feat(eslint-config-angular): add import rules

---

packages/eslint-config-angular/internal/base.js

Link: https://github.com/TinkoffCreditSystems/taiga-ui/pull/1035

fix(eslint-config-angular): ignore no-param-reassign

---

packages/eslint-config-angular/index.js
packages/eslint-config-angular/internal/base-typescript.js
packages/eslint-config-angular/internal/base.js
packages/eslint-config-angular/internal/extraneous-class.js
packages/eslint-config-angular/internal/import.js
packages/eslint-config-angular/internal/member-ordering.js
packages/eslint-config-angular/test/member-ordering/member-ordering-happy.test.js
packages/eslint-config-angular/test/member-ordering/member-ordering-unhappy.test.js

refactor(eslint-config-angular): reorganize rules group

---

packages/prettier-config/angular.js

feat(prettier-config): support readable formatting for yml files

---

packages/prettier-config/angular.js

feat(prettier-config): support readable formatting for md files

---

packages/eslint-config-angular/index.js
packages/eslint-config-angular/internal/base.js
packages/eslint-config-angular/internal/extraneous-class.js
packages/eslint-config-angular/internal/line-statements.js
packages/eslint-config-angular/test/line-statements/__fixtures__/line-statements-happy.fixture.ts
packages/eslint-config-angular/test/line-statements/__fixtures__/line-statements-unhappy.fixture.ts
packages/eslint-config-angular/test/line-statements/__snapshots__/line-statements-happy.test.js.snap
packages/eslint-config-angular/test/line-statements/__snapshots__/line-statements-unhappy.test.js.snap
packages/eslint-config-angular/test/line-statements/line-statements-happy.test.js
packages/eslint-config-angular/test/line-statements/line-statements-unhappy.test.js

feat(eslint-config-angular): support line statements

---

package-lock.json
package.json
packages/eslint-config/package.json
packages/linters/package.json
packages/prettier-config/angular.js
packages/prettier-config/package.json

feat(prettier-config): upgrade to new prettier version

---

package-lock.json
packages/eslint-config-angular/index.js
packages/eslint-config-angular/internal/html.js
packages/eslint-config-angular/package.json

Closed https://github.com/TinkoffCreditSystems/linters/issues/158
Support html

feat(eslint-config-angular): support html files

---

packages/eslint-config-angular/internal/base-typescript.js
packages/eslint-config-angular/internal/base.js

feat(eslint-config-angular): support member-accessibility

---

packages/eslint-config-angular/internal/base-typescript.js
packages/eslint-config-angular/internal/extraneous-class.js
packages/eslint-config-angular/internal/line-statements.js
packages/eslint-config-angular/internal/member-ordering.js
packages/eslint-config-angular/test/line-statements/line-statements-happy.test.js
packages/eslint-config-angular/test/line-statements/line-statements-unhappy.test.js
packages/eslint-config-angular/test/member-ordering/member-ordering-happy.test.js
packages/eslint-config-angular/test/member-ordering/member-ordering-unhappy.test.js

feat(eslint-config-angular): support no-inferrable-types, no-unused-vars

---

packages/eslint-config/internal/base.js

fix: Disabled old rule that did not allow the use for of

---

packages/eslint-config-angular/internal/import.js

fix(eslint-config-angular): overwrite consistent-type-imports

---

packages/eslint-config/internal/base.js

Dissable requery babel config file in project for simplify config

---

packages/eslint-config-angular/internal/base-typescript.js
packages/eslint-config-angular/internal/base.js

feat(eslint-config-angular): use recommendation rules

---

packages/eslint-config-angular/internal/base.js

fix(eslint-config-angular): support `no-return-assign`

---

packages/eslint-config-angular/internal/base.js

fix(eslint-config-angular): support `no-implicit-coercion`

---

packages/eslint-config-angular/internal/base.js

fix(eslint-config-angular): support `no-useless-rename`

---

package-lock.json
package.json
packages/eslint-config/package.json
packages/linters/package.json
packages/prettier-config/package.json

feat: upgrade prettier

---

package-lock.json
package.json
packages/linters/package.json
packages/prettier-config/package.json

fix(prettier-config): fix problem with less parser

---

package-lock.json
packages/eslint-config/package.json

fix(prettier-config): dedupe prettier 2.6.2

---

package-lock.json
packages/stylelint-config/package.json

feat(stylelint-config): upgrade stylelint

---

package-lock.json
packages/eslint-config-angular/README.md
packages/eslint-config-angular/package.json
packages/eslint-config-angular/rxjs/index.js

feat(eslint-config-angular): add rxjs plugin

---

packages/prettier-config/plugins/prettier-plugin-sort-package.js

fix(prettier-config): don't add scripts field if it's not provided

---

packages/eslint-config-angular/ts/base-typescript.js

feat(eslint-config-angular): support `@typescript-eslint/array-type`

---

packages/eslint-config-angular/ts/base-typescript.js

fix(eslint-config-angular): use `array-simple` instead of `array`

---

packages/eslint-config-angular/rxjs/index.js

https://github.com/Tinkoff/taiga-ui/blob/main/.eslintrc.js#L42

fix(eslint-config-angular): added recommended rules of best practices

---

packages/eslint-config-angular/README.md
packages/eslint-config-angular/package.json
packages/eslint-config-angular/promise/index.js

feat(eslint-config-angular): add most useful rules for async-await

---

packages/eslint-config-angular/ts/base.js

https://eslint.org/docs/rules/eqeqeq

feat(eslint-config-angular): support `eqeqeq`

---

packages/eslint-config/README.md

no tips for nx in doc
tips for nx now exsits

docs(eslint-config): add nx usage-tips

---

packages/eslint-config/internal/import.js
packages/eslint-config/test/import/__fixtures__/dep-a.js
packages/eslint-config/test/import/__fixtures__/dep-b.js
packages/eslint-config/test/import/__fixtures__/import-happy.fixture.js
packages/eslint-config/test/import/__fixtures__/import-unhappy.fixture.js
packages/eslint-config/test/import/__snapshots__/import-happy.test.js.snap
packages/eslint-config/test/import/__snapshots__/import-unhappy.test.js.snap
packages/eslint-config/test/import/import-happy.test.js
packages/eslint-config/test/import/import-unhappy.test.js

`import/no-cycle` is disabled
`import/no-cycle` is enabled

feat(eslint-config): set import/no-cycle to error

---

packages/linters/README.md

No info about deprecation on @tinkoff/linters package readme
readme contain deprecation badge and text description

docs(tinkoff-linters): add deprecation note

---

packages/eslint-config/errors/index.js
packages/eslint-config/internal/base.js

ci: move airbnb errors rules to separate config

---

package-lock.json
packages/eslint-config-angular/README.md
packages/eslint-config-angular/file-progess/index.js
packages/eslint-config-angular/package.json

Looks like prettier file progress

feat: add file-progress plugin

---

packages/eslint-config/README.md

docs(eslint-config): README.md fix typo

---

packages/eslint-config/README.md

not accurate tips for nx
more accurate recommendations for nx

docs(eslint-config): improve nx tips

---

packages/eslint-config-angular/recommended/base-typescript.js
packages/eslint-config-angular/recommended/base.js

prefer-destructuring rule in angular config
no prefer-destructuring rule in angular config

feat(eslint-config-angular): disable prefer-destructuring for *.js and *.ts

---

packages/stylelint-config/README.md

not clear - less/angular configs contains prettier or not?
described on what config based

docs(stylelint-config): describes basis of configs

---

packages/stylelint-config/less.js

fix(stylelint-config): ignore `fade`

---

packages/eslint-config-angular/recommended/base.js

fix(eslint-config-angular): exclude only dasherize files

---

packages/eslint-config-angular/.npmignore
packages/eslint-config-angular/README.md
packages/eslint-config-angular/experimental/index.js
packages/eslint-config-angular/function-return-type/index.js
packages/eslint-config-angular/package.json
packages/eslint-config-angular/recommended/base.js

feat(eslint-config-angular): add strict rules as experimental sub-package

---

packages/prettier-config/angular.js

fix(prettier-config): add `endOfLine` for angular config

---

packages/eslint-config-angular/experimental/index.js

feat(eslint-config-angular): add `sort-type-constituents`

---

packages/eslint-config-angular/experimental/index.js

feat(eslint-config-angular): support `dot-notation`

---

packages/eslint-config-angular/package.json
packages/eslint-config-react/package.json

- [-] Tests for the changes have been added (for bug fixes / features)
- [-] Docs have been added / updated (for bug fixes / features)
Eslint 7.5.0 as peerDependency
Eslint >= 7 as peerDependency

feat(eslint-config-react,eslint-config-angular): updated eslint as peerDependency

---

package-lock.json
packages/eslint-config-angular/README.md
packages/eslint-config-angular/html-eslint/index.js
packages/eslint-config-angular/package.json

feat(eslint-config-angular): add `html-eslint` plugin

---

package.json
packages/eslint-config-angular/package.json
packages/eslint-config-react/package.json
packages/eslint-config/package.json
packages/eslint-plugin/package.json
packages/linters/package.json
packages/prettier-config/package.json
packages/stylelint-config/package.json

chore: use correct github account in repo url

---

packages/typescript-config/README.md

docs(typescript-config): fix usage example

---

package-lock.json
packages/eslint-config-angular/package.json

See this https://github.com/BenoitZugmeyer/eslint-plugin-html/issues/176
And this https://github.com/Tinkoff/linters/issues/180
eslint-plugin-html is bumped, HTML rules work

chore(eslint-config-angular): bump eslint-plugin-html version
